[package]
name = "macropad-tool"
version = "0.0.1"
edition = "2021"
description = "Tool for programming macropad"

[dependencies]
anyhow = "1.0"
clap = { version = "4.2", features = ["derive"] }
enumset = "1.0"
env_logger = "0.10"
indoc = "1.0"
itertools = "0.10"
log = "0.4"
nom = "7.1"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
ron = "0.8"
rusb = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.2"
serde_yaml = "0.9"
strum = "0.24"
strum_macros = "0.24"
